apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-rules
spec:
  groups:
    - name: custom
      rules:
        - alert: ServiceNotActive
          annotations:
            description: Systemd unit "{{ $labels.name }}" is "{{ $labels.state }}", expected to be "active"
            summary: The service is expected to run, but it is not.
          expr: |-
            node_systemd_unit_state{name=~"(chronyd|k3s|tailscaled|zincati).service",state!="active"} != 0
          for: 5m
          labels:
            severity: warning
