---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: alertmanager-configs
spec:
  itemPath: "vaults/rhea/items/monitoring-alertmanager-configs"

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grafana-admin
spec:
  itemPath: "vaults/rhea/items/monitoring-grafana-admin"

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grafana-env
spec:
  itemPath: "vaults/rhea/items/monitoring-grafana-env"
