---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: alertmanager-configs
  itemPath: "vaults/rhea/items/wvogl5p3dfqqfnbem3vxqipluqk7hptal4wu2yioy7o5f2g7fopm"

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grafana-admin
  itemPath: "vaults/rhea/items/wvogl5p3dfqqfnbem3vxqipluqqis7hfh77cjhhkrsbwkdneluii"

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grafana-env
  itemPath: "vaults/rhea/items/wvogl5p3dfqqfnbem3vxqipluqs5bewoddgnmxgr7ctq5ve2l4ay"
