apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system
  destination:
    namespace: 1password
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://1password.github.io/connect-helm-charts"
    chart: connect
    targetRevision: 2.0.2
    helm:
      valuesObject:
        operator:
          create: true

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
