apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system
  destination:
    namespace: cilium
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://helm.cilium.io/"
    chart: cilium
    targetRevision: "1.17.6"
    helm:
      valuesObject:
        operator:
          replicas: 1
        kubeProxyReplacement: true
        k8sServiceHost: "100.102.81.94"
        k8sServicePort: 6443
        ipam:
          operator:
            clusterPoolIPv4PodCIDRList:
              - "10.42.0.0/16"
  ignoreDifferences:
    # can be removed once https://github.com/cilium/cilium/pull/37585 is released
    - kind: ConfigMap
      name: cilium-config
      jsonPointers:
        - /data/ipam-multi-pool-pre-allocation

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
