apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  project: system
  destination:
    namespace: ingress-nginx
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://kubernetes.github.io/ingress-nginx/"
    chart: ingress-nginx
    targetRevision: 4.12.0
    helm:
      valuesObject:
        controller:
          config:
            allow-snippet-annotations: "true"
          kind: DaemonSet
          hostPort:
            enabled: true
          service:
            enabled: false
          ingressClassResource:
            default: true
          metrics:
            enabled: true
            service:
              annotations:
                prometheus.io/scrape: "true"
                prometheus.io/port: "10254"

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
