apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vaultwarden

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: vaultwarden

resources:
  - namespace.yaml
  - statefulset.yaml
  - ingress.yaml

patches:
  - target:
      kind: StatefulSet
    patch: |-
      - op: replace
        path: /spec/revisionHistoryLimit
        value: 2
