apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: letsencrypt@mhutter.net
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - selector:
          dnsZones:
            - mhnet.app
            - mhnet.dev
        dns01:
          webhook:
            groupName: mhnet.app
            solverName: porkbun
            config:
              apiKeySecretRef:
                name: porkbun-key
                key: api-key
              secretKeySecretRef:
                name: porkbun-key
                key: secret-key
      - http01:
          ingress:
            ingressClassName: nginx
