---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-ingress-tls
spec:
  dnsNames:
    - id.mhnet.app
    - keycloak-admin.mhnet.dev
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: keycloak-ingress-tls
  usages:
    - digital signature
    - key encipherment
