---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: web
      port: 8443

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  replicas: 1
  revisionHistoryLimit: 3
  serviceName: miniflux
  template:
    spec:
      containers:
        - name: keycloak
          image: "ghcr.io/mhutter/mhnet-keycloak:v26.0.7-3"
          env:
            - name: KC_HOSTNAME
              value: "https://id.mhnet.app"
            # - name: KC_HOSTNAME_ADMIN
            #   value: "https://keycloak-admin.mhnet.dev"
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: /certs/tls.crt
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: /certs/tls.key
            - name: KC_PROXY_HEADERS
              value: xforwarded
          envFrom:
            - secretRef:
                name: keycloak-env
          volumeMounts:
            - name: tls
              readOnly: true
              mountPath: /certs
            - name: data
              mountPath: /opt/keycloak/data
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /health/ready
              port: 9000
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /health/live
              port: 9000
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
      securityContext:
        runAsNonRoot: true
        runAsUser: 142041
        runAsGroup: 142041
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: tls
          secret:
            secretName: keycloak-ingress-tls
        - name: data
          emptyDir: {}
