apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: keycloak

resources:
  - ./namespace.yaml
  - ./certificate.yaml
  - ./keycloak-env.sealed-secret.yaml
  - ./keycloak.yaml
  - ./ingress.yaml
