apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  destination:
    namespace: ai
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://github.com/mhutter/rhea.git"
    targetRevision: HEAD
    path: apps/ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
