apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbun
spec:
  project: apps
  destination:
    namespace: httpbun
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://github.com/mhutter/rhea.git"
    targetRevision: HEAD
    path: apps/httpbun
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
