apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
spec:
  project: apps
  destination:
    namespace: keycloak
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://github.com/mhutter/rhea.git"
    targetRevision: HEAD
    path: apps/keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
