---
apiVersion: v1
kind: Service
metadata:
  name: miniflux
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 8080

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: miniflux
spec:
  replicas: 1
  revisionHistoryLimit: 3
  serviceName: miniflux
  template:
    spec:
      containers:
        - name: miniflux
          image: "docker.io/miniflux/miniflux:2.2.5"
          envFrom:
            - secretRef:
                name: miniflux-env
          env:
            - name: LISTEN_ADDR
              value: "0.0.0.0:8080"
            - name: BASE_URL
              value: "https://feeds.mhnet.app/"
            - name: HTTPS
              value: "1"
            - name: CREATE_ADMIN
              value: "0"
            - name: OAUTH2_PROVIDER
              value: "oidc"
            - name: OAUTH2_REDIRECT_URL
              value: "https://feeds.mhnet.app/oauth2/oidc/callback"
            - name: OAUTH2_USER_CREATION
              value: "1"
            - name: RUN_MIGRATIONS
              value: "1"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
