apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: ai

resources:
  - ./namespace.yaml
  - ./ollama.yaml
  - ./open-webui.yaml
  - ./open-webui-env.sealed-secret.json
  - ./ingress.yaml
