---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: open-webui-env
spec:
  itemPath: "vaults/rhea/items/open-webui-env"

---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: open-webui
  ports:
    - name: web
      port: 8080

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: open-webui
spec:
  replicas: 1
  serviceName: open-webui
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
        - name: open-webui
          image: "ghcr.io/open-webui/open-webui:0.6.1"
          env:
            - name: OLLAMA_BASE_URL
              value: "http://100.112.141.2:11434"
            - name: CUSTOM_NAME
              value: mhnet AI
            - name: WEBUI_URL
              value: "https://ai.mhnet.app"
            - name: CORS_ALLOW_ORIGIN
              value: "https://ai.mhnet.app"
            - name: ENABLE_LOGIN_FORM
              value: "False"
            - name: ENABLE_OAUTH_SIGNUP
              value: "True"
            - name: OAUTH_PROVIDER_NAME
              value: mhnet IDP
            - name: ENABLE_OAUTH_ROLE_MANAGEMENT
              value: "True"
            - name: OAUTH_ADMIN_ROLES
              value: "admin"
          envFrom:
            - secretRef:
                name: open-webui-env
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: data
              mountPath: /app/backend/data
      securityContext:
        runAsNonRoot: true
        runAsUser: 172033
        runAsGroup: 172033
        seccompProfile:
          type: RuntimeDefault
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
