---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rr
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        {{- range .Values.services }}
        - {{ .domain | quote }}
        {{- end }}
      secretName: ingress-tls
  rules:
    {{- range $k, $v := .Values.services }}
    - host: {{ $v.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $k | quote }}
                port:
                  name: web
    {{- end }}
