---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: upgrade
  namespace: system-upgrade
spec:
  version: "v1.32.4+k3s1"
  concurrency: 1
  serviceAccountName: system-upgrade
  upgrade:
    image: docker.io/rancher/k3s-upgrade
  nodeSelector:
    matchExpressions:
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
          - k3s
