---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgres-creds
spec:
  itemPath: "vaults/rhea/items/2mr6hkdm63ywa4reg6qmfie3bq"

---
apiVersion: v1
kind: Service
metadata:
  name: psql
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: psql
      protocol: TCP
      port: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: psql
spec:
  serviceName: "psql"
  replicas: 1
  revisionHistoryLimit: 3
  template:
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: postgres
          image: "docker.io/library/postgres:17.6-alpine"
          args:
            - postgres
            - -c
            - config_file=/etc/postgresql/postgresql.conf
            - -c
            - listen_addresses=*
          ports:
            - containerPort: 5432
              name: psql
          env:
            - name: PGDATA
              value: /data/pgdata
          envFrom:
            - secretRef:
                name: postgres-creds
          volumeMounts:
            - name: pgdata
              mountPath: /data
            - name: config
              mountPath: /etc/postgresql
              readOnly: true
            - name: scripts
              mountPath: /scripts
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
      volumes:
        - name: config
          configMap:
            name: config
        - name: scripts
          configMap:
            name: scripts
            defaultMode: 0555
      securityContext:
        runAsNonRoot: true
        runAsUser: 181917
        runAsGroup: 181917
        seccompProfile:
          type: RuntimeDefault
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
