apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # Prevent ArgoCD removing Cilium CRs
  # see: https://docs.cilium.io/en/stable/configuration/argocd-issues/
  resource.exclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
      clusters:
        - "*"
  # Configure OIDC
  url: "https://argocd.mhnet.dev"
  oidc.config: |
    name: mhnet IDP
    issuer: https://id.mhnet.app/realms/mhnet
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
