apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # Configure OIDC
  url: "https://argocd.mhnet.dev"
  dex.config: |
    connectors:
      - type: oidc
        id: pocketid
        name: mhnet ID
        config:
          issuer: "https://id.mhnet.app"
          clientID: $oidc:clientID
          clientSecret: $oidc:clientSecret
          insecureEnableGroups: true
          scopes:
          - profile
          - email
          - groups
