apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # Prevent ArgoCD removing Cilium CRs
  # see: https://docs.cilium.io/en/stable/configuration/argocd-issues/
  resource.exclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
      clusters:
        - "*"
  # Configure OIDC
  url: "https://argocd.mhnet.dev"
  dex.config: |
    connectors:
      - type: oidc
        id: pocketid
        name: mhnet ID
        config:
          issuer: "https://id.mhnet.app"
          clientID: $oidc:clientID
          clientSecret: $oidc:clientSecret
          insecureEnableGroups: true
          scopes:
          - profile
          - email
          - groups
