apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# OIDC configuration: https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/keycloak/

resources:
  - namespace.yaml
  - secrets.yaml
  - "https://raw.githubusercontent.com/argoproj/argo-cd/v3.1.6/manifests/install.yaml"
  - ingress.yaml

patches:
  - path: ./argocd-cm.patch.yaml
  - path: ./argocd-rbac-cm.patch.yaml

  - target:
      kind: Service
      name: argocd-server
    patch: |-
      - op: add
        path: /metadata/annotations/traefik.ingress.kubernetes.io~1service.serverstransport
        value: argocd-argocd-server@kubernetescrd

  - target:
      kind: Daemonset
    patch: |-
      - op: replace
        path: /spec/revisionHistoryLimit
        value: 1
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/revisionHistoryLimit
        value: 1
  - target:
      kind: StatefulSet
    patch: |-
      - op: replace
        path: /spec/revisionHistoryLimit
        value: 1
