apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# OIDC configuration: https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/keycloak/

resources:
  - namespace.yaml
  - "https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.1/manifests/install.yaml"
  - ingress.yaml

patches:
  - path: ./argocd-cm.patch.yaml
  - path: ./argocd-rbac-cm.patch.yaml

  - target:
      kind: Daemonset
    patch: |-
      - op: replace
        path: /spec/revisionHistoryLimit
        value: 2
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/revisionHistoryLimit
        value: 2
  - target:
      kind: StatefulSet
    patch: |-
      - op: replace
        path: /spec/revisionHistoryLimit
        value: 2
